#########################
## Sample Sass Lint File
#########################

# Rule Configuration
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 0
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format: 
    - 2
    - 
      convention: 'hyphenatedbem'
      allow-leading-underscore: true
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  attribute-quotes: 0
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 0
  hex-length: 2
  hex-notation: 2
  indentation:
    - 0
    -
      size: 0
  leading-zero: 1
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth: 
    - 2
    -
      max-depth: 5
  property-sort-order:
    - 2
    - 
      order: alphabetical
  pseudo-element: 0
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 1
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 2
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 2
  final-newline: 0